CREATE TABLE FM_USER
(
    ID             INT AUTO_INCREMENT,
    CONSTRAINT     FM_USER_PK PRIMARY KEY (ID),
    USERNAME       VARCHAR(20) NOT NULL UNIQUE,
    PASSWORD       VARCHAR(100)  NOT NULL,
    ADMIN          TINYINT NOT NULL,
    ACTIVE         TINYINT NOT NULL
);

CREATE TABLE FM_PERIOD
(
    ID             INT AUTO_INCREMENT,
    CONSTRAINT     FM_PERIOD_PK PRIMARY KEY (ID),
    START_DATE     DATE NOT NULL,
    END_DATE       DATE NOT NULL,
    ACTIVE         TINYINT NOT NULL
);

CREATE TABLE INCOME
(
    ID             INT AUTO_INCREMENT,
    CONSTRAINT     INCOME_PK PRIMARY KEY (ID),
    FM_USER        INT,
    CONSTRAINT     INCOME_FM_USER_FK FOREIGN KEY (FM_USER) REFERENCES FM_USER(ID),
    FM_PERIOD      INT,
    CONSTRAINT     INCOME_FM_PERIOD_FK FOREIGN KEY (FM_PERIOD) REFERENCES FM_PERIOD(ID),
    AMOUNT         NUMERIC(11, 2) NOT NULL,
    SOURCE         VARCHAR(30) NOT NULL,
    COMMENT        VARCHAR(100)  NOT NULL
);

CREATE TABLE LOAN
(
    ID                INT AUTO_INCREMENT,
    CONSTRAINT        LOAN_PK PRIMARY KEY (ID),
    FM_USER           INT,
    CONSTRAINT        LOAN_FM_USER_FK FOREIGN KEY (FM_USER) REFERENCES FM_USER(ID),
    AMOUNT            NUMERIC(20, 2) NOT NULL,
    NAME              VARCHAR(30) NOT NULL,
    INTEREST_RATE     NUMERIC(5, 2) NOT NULL,
    MONTHLY_REPAYMENT NUMERIC(20, 2) NOT NULL
);

CREATE TABLE BALANCE
(
    ID                 INT AUTO_INCREMENT,
    CONSTRAINT         BALANCE_PK PRIMARY KEY (ID),
    FM_USER            INT,
    CONSTRAINT         BALANCE_FM_USER_FK FOREIGN KEY (FM_USER) REFERENCES FM_USER(ID),
    BALANCE            NUMERIC(12, 2) NOT NULL,
    INVESTMENT_BALANCE NUMERIC(12, 2) NOT NULL
);