INSERT INTO EXPENSE_CATEGORY (ID, CATEGORY, DISPLAY_NAME)
VALUES(1, 'FIX', 'Fix');

INSERT INTO EXPENSE_CATEGORY (ID, CATEGORY, DISPLAY_NAME)
VALUES(2, 'ESSENTIAL', 'Létfenntartás');

INSERT INTO EXPENSE_CATEGORY (ID, CATEGORY, DISPLAY_NAME)
VALUES(3, 'TRAVEL', 'Utazás');

INSERT INTO EXPENSE_CATEGORY (ID, CATEGORY, DISPLAY_NAME)
VALUES(4, 'FUN', 'Szórakozás');

INSERT INTO EXPENSE_CATEGORY (ID, CATEGORY, DISPLAY_NAME)
VALUES(5, 'ITEM', 'Tartós cikk');

INSERT INTO EXPENSE_CATEGORY (ID, CATEGORY, DISPLAY_NAME)
VALUES(6, 'INVESTMENT', 'Befektetés');

INSERT INTO ASSET_TYPE (ID, TYPE, DISPLAY_NAME)
VALUES(1, 'BOND', 'Kötvény');

INSERT INTO ASSET_TYPE (ID, TYPE, DISPLAY_NAME)
VALUES(2, 'SAVINGS_ACCOUNT', 'Lekötött betét');