INSERT INTO EXPENSE_CATEGORY (ID, CATEGORY)
VALUES(1, 'Fix');

INSERT INTO EXPENSE_CATEGORY (ID, CATEGORY)
VALUES(2, 'Létfenntartás');

INSERT INTO EXPENSE_CATEGORY (ID, CATEGORY)
VALUES(3, 'Utazás');

INSERT INTO EXPENSE_CATEGORY (ID, CATEGORY)
VALUES(4, 'Szórakozás');

INSERT INTO EXPENSE_CATEGORY (ID, CATEGORY)
VALUES(5, 'Tartós cikk');

INSERT INTO EXPENSE_CATEGORY (ID, CATEGORY)
VALUES(6, 'Befektetés');

INSERT INTO ASSET_TYPE (ID, TYPE)
VALUES(1, 'Forint (szabad pénz)');

INSERT INTO ASSET_TYPE (ID, TYPE)
VALUES(2, 'Kötvény');

INSERT INTO ASSET_TYPE (ID, TYPE)
VALUES(3, 'Lekötött betét');